In [35]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [9]:
data= ps.read_csv("car data.csv")
df=ps.DataFrame(data)

In [10]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0


In [11]:
df["CarAge"]=2023-df["Year"]

In [12]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,CarAge
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,9
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,10
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,6
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,12
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,9
...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0,7
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0,8
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0,14
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0,6


In [14]:
x=df[["CarAge","Kms_Driven","Fuel_Type","Seller_Type","Transmission"]]
x=ps.get_dummies(x)
y=df["Selling_Price"]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model=LinearRegression()
z=model.fit(x_train,y_train)
pre=model.predict(x_test)
pre

array([ 5.96066908,  5.32699541,  9.15259618, -0.28858822,  4.35880567,
       10.0697628 ,  0.86928662,  0.67054657,  1.2024395 ,  9.77857809,
       11.08846936,  0.27914813,  9.55324246,  6.34176254,  9.49919034,
        4.2488963 ,  0.09608958,  5.61659853,  1.50602155,  1.53828063,
        0.37323711, 10.4519002 ,  9.27660546,  3.88964322,  0.5943793 ,
        4.10182455,  4.28398253,  3.78659338,  1.49526853,  1.18451779,
        0.3553154 ,  9.69793039, -0.53213255,  2.88122372, 10.34631444,
        4.66060004,  4.21543646,  3.14268976,  4.28318501,  3.47584264,
        1.96689321,  6.22102366,  4.73228689,  0.51821202, 10.10980887,
        0.28362856,  4.63763337,  8.14446366,  4.40361443,  9.18784818,
        9.1788786 ,  1.52618348, 14.85203884, 15.55418802,  9.98457195,
       10.04143777,  5.07667668, 10.38669205,  2.35624857, 10.1117536 ,
        0.29258941])

In [15]:
from sklearn.metrics import r2_score,mean_squared_error
acc=r2_score(y_test,pre)
mse=mean_squared_error(y_test,pre)

In [22]:
acc

0.591149566336626

In [23]:
mse

9.418108720809972

In [24]:
model.intercept_

np.float64(8.983338776811973)

In [25]:
model.coef_

array([-2.79387747e-01, -4.48042783e-06, -2.55192308e+00,  3.85735270e+00,
       -1.30542962e+00,  2.05551251e+00, -2.05551251e+00,  2.40151693e+00,
       -2.40151693e+00])

In [29]:
print(df.iloc[5])

Car_Name         vitara brezza
Year                      2018
Selling_Price             9.25
Present_Price             9.83
Kms_Driven                2071
Fuel_Type               Diesel
Seller_Type             Dealer
Transmission            Manual
Owner                        0
CarAge                       5
Name: 5, dtype: object


In [30]:
x_train


,CarAge,Kms_Driven,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual
184,15,26000,False,False,True,False,True,False,True
132,6,3500,False,False,True,False,True,False,True
194,15,50000,False,False,True,False,True,False,True
75,8,36000,False,False,True,True,False,False,True
111,7,8700,False,False,True,False,True,False,True
...,...,...,...,...,...,...,...,...,...
188,10,18000,False,False,True,False,True,False,True
71,12,45000,False,True,False,True,False,False,True
106,9,16500,False,False,True,False,True,False,True
270,12,69341,False,False,True,True,False,False,True


In [31]:
pre1=model.predict([[5,2071,0,1,0,1,0,0,1]])


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [32]:
pre1

array([11.08846936])

# Write a program to create a Model using linear regression to predict the wine quality using the csv file provided named “winequality.csv”. Do the required process in the data before making a model. 

If you find any null value in “winequality.csv” then replace null value with mean value of respected columns.
Find co-efficient, intercept and mean squared error.
also Predict the quality of red wine for the following data:                       
fixed acidity: 8            
volatile acidity: 0.4      
citric acid: 0.40                
residual sugar: 15          
chlorides: 0.048                  
free sulfur dioxide: 40      
total sulfur dioxide: 150     
density: 0.99                  
pH: 3                      
sulphates: 0.45                
alcohol: 10.5

In [62]:
data=pd.read_csv("winequalityN.csv")
data

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5


In [61]:
df=pd.DataFrame(data)
df=pd.get_dummies(df)
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type_red,type_white
0,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6,False,True
1,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6,False,True
2,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6,False,True
3,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,False,True
4,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,True,False
6493,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6,True,False
6494,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,True,False
6495,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,True,False


In [63]:
df.fillna(df.mean(),inplace=True)

In [72]:
x=df[["fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol","type_red"]]
y=df["quality"]

In [73]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model=LinearRegression()
z=model.fit(x_train,y_train)
pre=model.predict(x_test)
pre

array([6.34992927, 6.02349546, 5.76827822, ..., 5.58298533, 5.68576899,
       5.43735072], shape=(1300,))

In [74]:
from sklearn.metrics import r2_score,mean_squared_error
acc=r2_score(y_test,pre)
mse=mean_squared_error(y_test,pre)

In [75]:
acc

0.3404845408986844

In [76]:
x_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type_red
1916,6.6,0.25,0.36,8.1,0.045,54.0,180.0,0.99580,3.08,0.42,9.2,False
947,8.5,0.16,0.35,1.6,0.039,24.0,147.0,0.99350,2.96,0.36,10.0,False
877,6.0,0.28,0.34,1.6,0.119,33.0,104.0,0.99210,3.19,0.38,10.2,False
2927,7.0,0.31,0.31,9.1,0.036,45.0,140.0,0.99216,2.98,0.31,12.0,False
6063,8.5,0.44,0.50,1.9,0.369,15.0,38.0,0.99634,3.01,1.10,9.4,True
...,...,...,...,...,...,...,...,...,...,...,...,...
3772,6.3,0.24,0.29,13.7,0.035,53.0,134.0,0.99567,3.17,0.38,10.6,False
5191,6.9,0.36,0.25,2.4,0.098,5.0,16.0,0.99640,3.41,0.60,10.1,True
5226,13.4,0.27,0.62,2.6,0.082,6.0,21.0,1.00020,3.16,0.67,9.7,True
5390,8.9,0.40,0.51,2.6,0.052,13.0,27.0,0.99500,3.32,0.90,13.4,True


In [78]:
pre1=model.predict([[8,0.4,0.4,15,0.048,40,150,0.99,3,0.45,10.5,1]])


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [94]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import  accuracy_score


In [95]:
data = pd.read_csv("Fish.csv")
df=pd.DataFrame(data)

In [96]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)
pre = model.predict(x_test)
acc=accuracy_score(y_test,pre)

In [97]:
acc

0.4748717948717949

In [107]:
for i in range(1,11):
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train,y_train)
    pre = model.predict(x_test)
    acc=accuracy_score(y_test,pre)
    print(acc)

0.5641025641025641
0.48923076923076925
0.4748717948717949
0.4748717948717949
0.4625641025641026
0.4605128205128205
0.4676923076923077
0.47794871794871796
0.46205128205128204
0.46205128205128204


In [84]:
df

,Species,Weight,Length1,Length2,Length3,Height,Width
0,Bream,242.0,23.2,25.4,30.0,11.5200,4.0200
1,Bream,290.0,24.0,26.3,31.2,12.4800,4.3056
2,Bream,340.0,23.9,26.5,31.1,12.3778,4.6961
3,Bream,363.0,26.3,29.0,33.5,12.7300,4.4555
4,Bream,430.0,26.5,29.0,34.0,12.4440,5.1340
...,...,...,...,...,...,...,...
154,Smelt,12.2,11.5,12.2,13.4,2.0904,1.3936
155,Smelt,13.4,11.7,12.4,13.5,2.4300,1.2690
156,Smelt,12.2,12.1,13.0,13.8,2.2770,1.2558
157,Smelt,19.7,13.2,14.3,15.2,2.8728,2.0672


In [108]:
data={
    "movie":["m1","m2","m3","m4"],
    "duration":[150,120,150,110],
    "alevel":[1,2,3,4],
    "type":["action","comedy","comedy","action"]
}


In [110]:
df1=pd.DataFrame(data)

In [111]:
df1

,movie,duration,alevel,type
0,m1,150,1,action
1,m2,120,2,comedy
2,m3,150,3,comedy
3,m4,110,4,action


In [114]:
x=df1[["duration","alevel"]]
y=df1["type"]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)
model = KNeighborsClassifier(n_neighbors=1)
model.fit(x_train,y_train)
pre = model.predict(x_test)
acc=accuracy_score(y_test,pre)

In [115]:
acc

0.0